version: '3'
services:
  demo-app:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - .:/src
    command: sh -c 'cd app && yarn start'
    ports:
      - "80:80"
    tty: true
